# root
jenkins:
  systemMessage: "Automating Configuration Appeals Devops Jenkins"
  securityRealm:
    github:
      githubWebUri: "https://github.com"
      githubApiUri: "https://api.github.com"
      clientID: "<client_id>"
      clientSecret: "<client_secret>"
      oauthScopes: "read:org"
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    github:
      adminUserNames: "<admins>"
      allowAnonymousJobStatusPermission: false
      allowAnonymousReadPermission: true
      allowCcTrayPermission: false
      allowGithubWebHookPermission: true
      authenticatedUserCreateJobPermission: false
      authenticatedUserReadPermission: false
      organizationNames: "<github_org_name>"
      useRepositoryPermissions: false
  disableRememberMe: true
  mode: NORMAL
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  views:
  - all:
      name: "all"
  globalNodeProperties:
  - envVars:
      env:
      - key: "AWS_DEFAULT_REGION"
        value: "<aws_region>"
      - key: "ACCOUNT_ENV"
        value: "<account_env>"
      - key: "PATH"
        value: "/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/dsva/.local/bin:/home/dsva/bin"
  labelString: "appeals deploy devops"
  mode: NORMAL
  numExecutors: 16
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0

#root
credentials:
  system:
    domainCredentials:
      - credentials:
        - string:
            scope: GLOBAL
            id: "SLACK_TEAM_DOMAIN"
            secret: "<jenkins.slack_team_domain>"
            description: "DSVA team on Slack"
        # - string:
        #     scope: GLOBAL
        #     id: "SLACK_TOKEN"
        #     secret: "<jenkins.slack_token>"
        #     description: "Slack token"
        # - string:
        #     scope: GLOBAL
        #     id: "DEPLOY_SLACK_TOKEN"
        #     secret: "<jenkins.slack_token>"
        #     description: "Deploy Slack token"
        # - string:
        #     scope: GLOBAL
        #     id: "ALERT_SLACK_TOKEN"
        #     secret: "<jenkins.slack_token>"
        #     description: "Alert Slack Token"
        # - string:
        #     scope: GLOBAL
        #     id: "TEST_SLACK_TOKEN"
        #     secret: "<jenkins.slack_token>"
        #     description: "Test Slack token"
        - string:
            scope: GLOBAL
            id: "VAEC_SLACK_TOKEN"
            secret: "<jenkins.slack_token>"
            description: "Vaec Slack token"
        # Temporarily remove dsva related slack channels for initial vaec jenkins deployment
        # - string:
        #     scope: GLOBAL
        #     id: "SLACK_CHANNEL"
        #     secret: "<jenkins.slack_channel>"
        #     description: "Regular Slack Channel"
        # - string:
        #     scope: GLOBAL
        #     id: "DEPLOY_CHANNEL"
        #     secret: "<jenkins.deploy_channel>"
        #     description: "Deploy Slack Channel"
        # - string:
        #     scope: GLOBAL
        #     id: "ALERT_SLACK_CHANNEL"
        #     secret: "<jenkins.alert_channel>"
        #     description: "Alert Slack Channel"
        # - string:
        #     scope: GLOBAL
        #     id: "TEST_SLACK_CHANNEL"
        #     secret: "<jenkins.test_channel>"
        #     description: "Test Slack Channel"
        # add a new entry for the vaec specific slack alert channel
        - string:
           scope: GLOBAL
           id: "VAEC_SLACK_CHANNEL"
           secret: "<jenkins.vaec_channel>"
           description: "VAEC Alert Slack Channel"

        - usernamePassword:
            scope: GLOBAL
            id: "va-bot"
            username: "va-bot"
            password: "<devops.github_api_token>"
            description: "va-bot username/password"
        - string:
            scope: GLOBAL
            id: "GIT_CREDENTIAL"
            secret: "<devops.github_api_token>"
            description: "va-bot personal access token"

# root
tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git

# root
unclassified:
  location:
    adminAddress: "<admin_email>"
    url: "http://<ip>"
  slackNotifier:
    teamDomain: "dsva"
    baseUrl: ""
    tokenCredentialId: "VAEC_SLACK_TOKEN"
    botUser: true
    room: "#appeals-alerts-vaec"
    #room: "#appeals-deployment"
  globalLibraries:
    libraries:
      - name: "appeals-devops-jenkins"
        #set to VAEC branch for initial Jenkins deployment
        defaultVersion: "main"
        implicit: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/department-of-veterans-affairs/appeals-devops-jenkins.git"
                credentialsId: "va-bot"

# root
jobs:
  - script: >
        job('seed-job'){
            displayName('seed-job')
            logRotator {
              numToKeep(15)
            }
            wrappers {
                credentialsBinding {
                    string('GIT_CREDENTIAL', 'GIT_CREDENTIAL')
                }
            }
            steps {
                dsl(['seedJob.groovy'])
            }
            parameters {
                stringParam('DEPLOYMENT_DEV_BRANCH', 'main', 'appeals-deployment branch')                
            }
            triggers {
                cron('H H(0-5) * * *')
            }
        }
  # - script: >
  #     queue('seed-job')
