name: Groovy Linter

on:
  push:
    branches:
      - f-gh-migration

jobs:
  groovy-linter:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up node install dir
        run: mkdir -p ~/.local/bin && npm config set prefix '~/.local' 

      - name: Install and run latest version of npm-groovy-lint
        run: npm install -g npm-groovy-lint

      - name: groovy-lint
        run: |
          ls -la ~/.local/bin
          npm-groovy-lint --failon warning

